"""
Analytics Agent
---------------
Responsible for analyzing validated sales datasets
and producing structured metrics and actionable insights.
"""

from pathlib import Path
import pandas as pd


class AnalyticsAgent:
    """Agent responsible for analytical processing."""

    def __init__(
        self,
        dataset_path: str,
        task_id: str = "task_001",
    ):
        self.dataset_path = Path(dataset_path)
        self.task_id = task_id

    def load_data(self) -> pd.DataFrame:
        """Load the dataset without modifying the original file."""

        if not self.dataset_path.exists():
            raise FileNotFoundError(
                f"Dataset não encontrado: {self.dataset_path}"
            )

        return pd.read_csv(self.dataset_path)

    def calculate_metrics(self, df: pd.DataFrame) -> list:
        """Calculate the main sales metrics."""

        metrics = []

        if "total_sales" in df.columns:
            metrics.append(
                {
                    "name": "total_sales",
                    "value": round(float(df["total_sales"].sum()), 2),
                    "description": "Total sales value.",
                }
            )

        if "quantity" in df.columns:
            metrics.append(
                {
                    "name": "total_quantity",
                    "value": int(df["quantity"].sum()),
                    "description": "Total quantity sold.",
                }
            )

        if "order_id" in df.columns:
            metrics.append(
                {
                    "name": "total_orders",
                    "value": int(df["order_id"].nunique()),
                    "description": "Number of unique orders.",
                }
            )

        if "unit_price" in df.columns and not df.empty:
            metrics.append(
                {
                    "name": "average_unit_price",
                    "value": round(float(df["unit_price"].mean()), 2),
                    "description": "Average unit price.",
                }
            )

        if "store" in df.columns:
            metrics.append(
                {
                    "name": "stores",
                    "value": int(df["store"].nunique()),
                    "description": "Number of stores represented in the dataset.",
                }
            )

        return metrics

    def generate_insights(self, df: pd.DataFrame) -> list:
        """Generate structured analytical insights."""

        insights = []

        if "total_sales" in df.columns and not df.empty:
            total_sales = float(df["total_sales"].sum())

            insights.append(
                {
                    "type": "sales_summary",
                    "description": (
                        f"Total sales generated by the dataset: "
                        f"{total_sales:.2f}."
                    ),
                    "severity": "LOW",
                }
            )

        if "store" in df.columns and "total_sales" in df.columns:
            sales_by_store = (
                df.groupby("store")["total_sales"]
                .sum()
                .sort_values(ascending=False)
            )

            if not sales_by_store.empty:
                top_store = sales_by_store.index[0]
                top_sales = float(sales_by_store.iloc[0])

                insights.append(
                    {
                        "type": "top_store",
                        "description": (
                            f"Store '{top_store}' generated the highest "
                            f"sales value of {top_sales:.2f}."
                        ),
                        "severity": "LOW",
                    }
                )

        if "category" in df.columns and "total_sales" in df.columns:
            sales_by_category = (
                df.groupby("category")["total_sales"]
                .sum()
                .sort_values(ascending=False)
            )

            if not sales_by_category.empty:
                top_category = sales_by_category.index[0]

                insights.append(
                    {
                        "type": "top_category",
                        "description": (
                            f"Category '{top_category}' generated "
                            "the highest sales value."
                        ),
                        "severity": "LOW",
                    }
                )

        return insights

    def run(self) -> dict:
        """Execute the analytical process."""

        try:
            df = self.load_data()

            metrics = self.calculate_metrics(df)
            insights = self.generate_insights(df)

            return {
                "agent": "analytics_agent",
                "status": "COMPLETED",
                "task_id": self.task_id,
                "dataset": str(self.dataset_path),
                "rows": int(len(df)),
                "columns": int(len(df.columns)),
                "metrics": metrics,
                "insights": insights,
            }

        except Exception as exc:
            return {
                "agent": "analytics_agent",
                "status": "ERROR",
                "task_id": self.task_id,
                "dataset": str(self.dataset_path),
                "metrics": [],
                "insights": [],
                "error": {
                    "type": type(exc).__name__,
                    "message": str(exc),
                },
            }


if __name__ == "__main__":
    agent = AnalyticsAgent("data/sales.csv")

    report = agent.run()

    print(report)
